In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
import seaborn as sns
from scipy import stats
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
seed=42

In [2]:
data = pd.read_csv("DataGood.csv")
data = data.drop(['NB1'], axis = 1)
data = data.drop(['NB2'], axis = 1)
data = data.drop(['CLIENTNUM'], axis = 1)

In [3]:
x = data.drop(['Attrition_Flag'], axis = 1)
y = pd.DataFrame(data['Attrition_Flag'])

categorical_columns = ['Gender', 'Education_Level', 'Marital_Status', 'Income_Category', 'Card_Category']
x_encoded = pd.get_dummies(x, columns=categorical_columns)

In [4]:
x_train, x_test, y_train, y_test = train_test_split(x_encoded, y, test_size=0.2, random_state=seed, shuffle=True)

x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size=0.15, random_state=seed, shuffle=True)

In [5]:
print('K-Nearest Neighbors')
clf = KNeighborsClassifier()
scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)
clf.fit(x_train_scaled, y_train)

x_val_scaled = scaler.transform(x_val)
y_hat = clf.predict(x_val_scaled)

accuracy = accuracy_score(y_val, y_hat)
confusion = confusion_matrix(y_val, y_hat)

print(f'Accuracy: {accuracy:.2f}')
print('Confusion Matrix:')
print(confusion)

K-Nearest Neighbors
Accuracy: 0.87
Confusion Matrix:
[[542   7]
 [ 80  42]]


C:\Users\Leonardo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\neighbors\_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [6]:
res=[]
for n_neighbors in range(1, 11):
    for weights in ['uniform', 'distance']:
        clf = KNeighborsClassifier(n_neighbors=n_neighbors, weights=weights)
        scaler = StandardScaler()

        x_train_scaled = scaler.fit_transform(x_train)
        clf.fit(x_train_scaled, y_train)
        y_hat = clf.predict(scaler.transform(x_val))

        accuracy = accuracy_score(y_val, y_hat)
        precision = precision_score(y_val, y_hat)
        recall = recall_score(y_val, y_hat)
        f1 = f1_score(y_val, y_hat)

        print(f'{n_neighbors=}, {weights=}, {accuracy=}, {precision=}, {recall=}, {f1=}')
        res.append({
            'n_neighbors': n_neighbors,
            'weights': weights,
            'Accuracy': accuracy,
            'Precision': precision,
            'Recall': recall,
            'F1-score': f1
        })

C:\Users\Leonardo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\neighbors\_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\Leonardo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\neighbors\_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\Leonardo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\neighbors\_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please

n_neighbors=1, weights='uniform', accuracy=0.8524590163934426, precision=0.6236559139784946, recall=0.47540983606557374, f1=0.5395348837209303
n_neighbors=1, weights='distance', accuracy=0.8524590163934426, precision=0.6236559139784946, recall=0.47540983606557374, f1=0.5395348837209303
n_neighbors=2, weights='uniform', accuracy=0.8524590163934426, precision=0.8108108108108109, recall=0.2459016393442623, f1=0.37735849056603776
n_neighbors=2, weights='distance', accuracy=0.8524590163934426, precision=0.6236559139784946, recall=0.47540983606557374, f1=0.5395348837209303


C:\Users\Leonardo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\neighbors\_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\Leonardo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\neighbors\_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\Leonardo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\neighbors\_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please

n_neighbors=3, weights='uniform', accuracy=0.8703427719821163, precision=0.8070175438596491, recall=0.3770491803278688, f1=0.5139664804469273
n_neighbors=3, weights='distance', accuracy=0.8703427719821163, precision=0.8070175438596491, recall=0.3770491803278688, f1=0.5139664804469273
n_neighbors=4, weights='uniform', accuracy=0.8509687034277198, precision=0.8235294117647058, recall=0.22950819672131148, f1=0.358974358974359
n_neighbors=4, weights='distance', accuracy=0.8748137108792846, precision=0.8064516129032258, recall=0.4098360655737705, f1=0.5434782608695652
n_neighbors=5, weights='uniform', accuracy=0.8703427719821163, precision=0.8571428571428571, recall=0.3442622950819672, f1=0.49122807017543857
n_neighbors=5, weights='distance', accuracy=0.8703427719821163, precision=0.8571428571428571, recall=0.3442622950819672, f1=0.49122807017543857
n_neighbors=6, weights='uniform', accuracy=0.8464977645305514, precision=0.8275862068965517, recall=0.19672131147540983, f1=0.3178807947019867


C:\Users\Leonardo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\neighbors\_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\Leonardo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\neighbors\_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\Leonardo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\neighbors\_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please

n_neighbors=7, weights='distance', accuracy=0.856929955290611, precision=0.8095238095238095, recall=0.2786885245901639, f1=0.4146341463414634
n_neighbors=8, weights='uniform', accuracy=0.8479880774962743, precision=0.8846153846153846, recall=0.1885245901639344, f1=0.3108108108108108
n_neighbors=8, weights='distance', accuracy=0.8658718330849479, precision=0.8333333333333334, recall=0.32786885245901637, f1=0.4705882352941176
n_neighbors=9, weights='uniform', accuracy=0.856929955290611, precision=0.8611111111111112, recall=0.2540983606557377, f1=0.3924050632911393
n_neighbors=9, weights='distance', accuracy=0.856929955290611, precision=0.8611111111111112, recall=0.2540983606557377, f1=0.3924050632911393
n_neighbors=10, weights='uniform', accuracy=0.8464977645305514, precision=0.88, recall=0.18032786885245902, f1=0.29931972789115646
n_neighbors=10, weights='distance', accuracy=0.8673621460506706, precision=0.8837209302325582, recall=0.3114754098360656, f1=0.4606060606060607


C:\Users\Leonardo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\neighbors\_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\Leonardo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\neighbors\_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [7]:
res_df = pd.DataFrame(res)
sorted_df = res_df.sort_values('Accuracy', ascending=False)
sorted_df

n_neighbors   weights  Accuracy  Precision    Recall  F1-score
7             4  distance  0.874814   0.806452  0.409836  0.543478
4             3   uniform  0.870343   0.807018  0.377049  0.513966
5             3  distance  0.870343   0.807018  0.377049  0.513966
8             5   uniform  0.870343   0.857143  0.344262  0.491228
9             5  distance  0.870343   0.857143  0.344262  0.491228
11            6  distance  0.870343   0.830189  0.360656  0.502857
19           10  distance  0.867362   0.883721  0.311475  0.460606
15            8  distance  0.865872   0.833333  0.327869  0.470588
17            9  distance  0.856930   0.861111  0.254098  0.392405
16            9   uniform  0.856930   0.861111  0.254098  0.392405
13            7  distance  0.856930   0.809524  0.278689  0.414634
12            7   uniform  0.855440   0.804878  0.270492  0.404908
0             1   uniform  0.852459   0.623656  0.475410  0.539535
1             1  distance  0.852459   0.623656  0.475410  0.539535
3             2  distance  0.852459   0.623656  0.475410  0.539535
2             2   uniform  0.852459   0.810811  0.245902  0.377358
6             4   uniform  0.850969   0.823529  0.229508  0.358974
14            8   uniform  0.847988   0.884615  0.188525  0.310811
18           10   uniform  0.846498   0.880000  0.180328  0.299320
10            6   uniform  0.846498   0.827586  0.196721  0.317881

In [8]:
res_df.iloc[res_df.Accuracy.argmax()]

n_neighbors           4
weights        distance
Accuracy       0.874814
Precision      0.806452
Recall         0.409836
F1-score       0.543478
Name: 7, dtype: object

In [9]:
n_neighbors=4
weights='distance'

In [10]:
print(f'K-Nearest Neighbors, {n_neighbors=}, {weights=}')
clf = KNeighborsClassifier(n_neighbors=n_neighbors, weights=weights)
scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)
clf.fit(x_train_scaled, y_train)

x_val_scaled = scaler.transform(x_val)
y_hat_val = clf.predict(x_val_scaled)
accuracy_val = accuracy_score(y_val, y_hat_val)
precision_val = precision_score(y_val, y_hat_val)
print(f'VAL: {accuracy_val=}, {precision_val=}')

x_test_scaled = scaler.transform(x_test)
y_hat_test = clf.predict(x_test_scaled)
accuracy_test = accuracy_score(y_test, y_hat_test)
precision_test = precision_score(y_test, y_hat_test)
print(f'TEST: {accuracy_test=}, {precision_test=}')

K-Nearest Neighbors, n_neighbors=4, weights='distance'
VAL: accuracy_val=0.8748137108792846, precision_val=0.8064516129032258
TEST: accuracy_test=0.8756708407871199, precision_test=0.6597938144329897


C:\Users\Leonardo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\neighbors\_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [11]:
confusion_val = confusion_matrix(y_val, y_hat_val)
confusion_test = confusion_matrix(y_test, y_hat_test)

In [12]:
print(confusion_val)

[[537  12]
 [ 72  50]]


In [13]:
print(confusion_test)

[[915  33]
 [106  64]]
