In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
import seaborn as sns
from scipy import stats
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.naive_bayes import GaussianNB


seed=42

In [2]:
data = pd.read_csv("DataGood.csv")
data = data.drop(['NB1'], axis = 1)
data = data.drop(['NB2'], axis = 1)
data = data.drop(['CLIENTNUM'], axis = 1)

In [3]:
x = data.drop(['Attrition_Flag'], axis = 1)
y = pd.DataFrame(data['Attrition_Flag'])

categorical_columns = ['Gender', 'Education_Level', 'Marital_Status', 'Income_Category', 'Card_Category']
x_encoded = pd.get_dummies(x, columns=categorical_columns)


In [4]:
x_train, x_test, y_train, y_test = train_test_split(x_encoded, y, test_size=0.2, random_state=seed, shuffle=True)

x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size=0.15, random_state=seed, shuffle=True)

In [5]:
clf = GaussianNB()
scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)
clf.fit(x_train_scaled, y_train)

x_val_scaled = scaler.transform(x_val)
y_hat = clf.predict(x_val_scaled)

accuracy = accuracy_score(y_val, y_hat)
confusion = confusion_matrix(y_val, y_hat)

print(f'Accuracy: {accuracy:.2f}')
print('Confusion Matrix:')
print(confusion)


Accuracy: 0.87
Confusion Matrix:
[[505  44]
 [ 42  80]]


C:\Users\Leonardo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [6]:
res = []

for var_smoothing in np.logspace(start=-3, stop=3, num=10, base=10, endpoint=True):
    clf = GaussianNB(var_smoothing=var_smoothing)
    scaler = StandardScaler()

    x_train_scaled = scaler.fit_transform(x_train)
    clf.fit(x_train_scaled, y_train)

    x_val_scaled = scaler.transform(x_val)
    y_hat = clf.predict(x_val_scaled)

    accuracy = accuracy_score(y_val, y_hat)
    precision = precision_score(y_val, y_hat)
    recall = recall_score(y_val, y_hat)
    f1 = f1_score(y_val, y_hat)

    print(f'{var_smoothing=}, {accuracy=}, {precision=}, {recall=}, {f1=}')
    res.append({
        'var_smoothing': var_smoothing,
        'Accuracy': accuracy,
        'Precision': precision,
        'Recall': recall,
        'F1-score': f1
    })

C:\Users\Leonardo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Leonardo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Leonardo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please chang

var_smoothing=0.001, accuracy=0.8718330849478391, precision=0.6451612903225806, recall=0.6557377049180327, f1=0.6504065040650406
var_smoothing=0.004641588833612777, accuracy=0.8718330849478391, precision=0.6451612903225806, recall=0.6557377049180327, f1=0.6504065040650406
var_smoothing=0.021544346900318832, accuracy=0.8718330849478391, precision=0.6475409836065574, recall=0.6475409836065574, f1=0.6475409836065574
var_smoothing=0.1, accuracy=0.8748137108792846, precision=0.6610169491525424, recall=0.639344262295082, f1=0.65
var_smoothing=0.46415888336127775, accuracy=0.8777943368107303, precision=0.7222222222222222, recall=0.5327868852459017, f1=0.6132075471698113
var_smoothing=2.154434690031882, accuracy=0.8286140089418778, precision=0.8888888888888888, recall=0.06557377049180328, f1=0.12213740458015268
var_smoothing=10.0, accuracy=0.8181818181818182, precision=0.0, recall=0.0, f1=0.0
var_smoothing=46.41588833612773, accuracy=0.8181818181818182, precision=0.0, recall=0.0, f1=0.0
var_sm

C:\Users\Leonardo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Leonardo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Leonardo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d arra

In [9]:
res_df = pd.DataFrame(res)
sorted_df = res_df.sort_values('Accuracy', ascending=False)
sorted_df

var_smoothing  Accuracy  Precision    Recall  F1-score
4       0.464159  0.877794   0.722222  0.532787  0.613208
3       0.100000  0.874814   0.661017  0.639344  0.650000
0       0.001000  0.871833   0.645161  0.655738  0.650407
1       0.004642  0.871833   0.645161  0.655738  0.650407
2       0.021544  0.871833   0.647541  0.647541  0.647541
5       2.154435  0.828614   0.888889  0.065574  0.122137
6      10.000000  0.818182   0.000000  0.000000  0.000000
7      46.415888  0.818182   0.000000  0.000000  0.000000
8     215.443469  0.818182   0.000000  0.000000  0.000000
9    1000.000000  0.818182   0.000000  0.000000  0.000000

In [10]:
res_df.iloc[res_df.Accuracy.argmax()]

var_smoothing    0.464159
Accuracy         0.877794
Precision        0.722222
Recall           0.532787
F1-score         0.613208
Name: 4, dtype: float64

In [12]:
var_smoothing = 0.464159

In [13]:
print(f'Naive Bayes,{var_smoothing=}')
clf = GaussianNB(var_smoothing=var_smoothing)
scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)
clf.fit(x_train_scaled, y_train)

x_val_scaled = scaler.transform(x_val)
y_hat_val = clf.predict(x_val_scaled)
accuracy_val = accuracy_score(y_val, y_hat_val)
precision_val = precision_score(y_val, y_hat_val)
print(f'VAL: {accuracy_val=}, {precision_val=}')

x_test_scaled = scaler.transform(x_test)
y_hat_test = clf.predict(x_test_scaled)
accuracy_test = accuracy_score(y_test, y_hat_test)
precision_test = precision_score(y_test, y_hat_test)
print(f'TEST: {accuracy_test=}, {precision_test=}')

Naive Bayes,var_smoothing=0.464159
VAL: accuracy_val=0.8777943368107303, precision_val=0.7222222222222222
TEST: accuracy_test=0.872093023255814, precision_test=0.608


C:\Users\Leonardo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [14]:
confusion_val = confusion_matrix(y_val, y_hat_val)
confusion_test = confusion_matrix(y_test, y_hat_test)

In [15]:
print(confusion_val)

[[524  25]
 [ 57  65]]


In [16]:
print(confusion_test)

[[899  49]
 [ 94  76]]
